[toolchain]
channel = "stable"
targets = [
    "aarch64-apple-ios",
    "wasm32-unknown-unknown",
    "x86_64-unknown-linux-gnu",
    "x86_64-apple-darwin",
    "x86_64-apple-ios",
    "x86_64-pc-windows-gnu"
]
profile = "minimal"
